### ISSUE TITLE
Erro ao notificar widget fora da árvore utilizando BloC e Provider (AccountPage)

### ISSUE THREAD

**Issue by rodrigoqb** [balta-io/7186#1]
Olá!

Estou seguindo a implementação do curso, porém, me deparei com um problema.

Ao clicar em "Autentique-se", presente na account.page.dart (unauthenticated-user-card.widget.dart), informar o usuário para autenticação e clicar em "Entrar", estou recebendo o seguinte erro:

```
Unhandled Exception: 'package:provider/src/provider.dart': Failed assertion: line 191 pos 7: 'context.owner.debugBuilding || listen == false || debugIsInInheritedProviderUpdate': Tried to listen to a value exposed with provider, from outside of the widget tree.

This is likely caused by an event handler (like a button's onPressed) that called
Provider.of without passing `listen: false`.

To fix, write:
Provider.of<UserBloc>(context, listen: false);

It is unsupported because may pointlessly rebuild the widget associated to the
event handler, when the widget tree doesn't care about the value.
```

Caso eu aplique a solução citada acima, adicionar o "listen: false", o projeto não acusa mais o erro, porém, não atualiza o widget da account.page.dart ao ser redirecionado com o usuário autenticado:

Método authenticate() da login.page.dart:
```
authenticate(BuildContext context) async {
    var bloc = Provider.of<UserBloc>(context, listen: false);

    var user = await bloc.authenticate(
      new AuthenticateModel(
        username: username,
        password: password,
      ),
    );

    if (user != null) {
      Navigator.pop(context);
      return;
    }

    final snackBar = SnackBar(content: Text('Usuário ou senha invalidos'));
    _scaffoldKey.currentState.showSnackBar(snackBar);
  }
```

AccountPage
```
class AccountPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    var bloc = Provider.of<UserBloc>(context);

    return Scaffold(
      appBar: AppBar(
        actions: <Widget>[
          FlatButton(
            child: Icon(
              Icons.settings,
            ),
            onPressed: () {
              Navigator.push(
                context,
                MaterialPageRoute(
                  builder: (context) => SettingsPage(),
                ),
              );
            },
          )
        ],
      ),
      body: bloc.user == null
          ? UnauthenticatedUserCard()
          : AuthenticatedUserCard(),
    );
  }
}
```

Segue trecho da botão da login.page.dart, e main.dart:

Botão para "Entrar" na login.page.dart:
```
FlatButton(
                child: Text("Entrar"),
                onPressed: () {
                  if (_formKey.currentState.validate()) {
                    _formKey.currentState.save();
                    authenticate(context);
                  }
                },
              ),
```

main.dart
```
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider<HomeBloc>.value(
          value: HomeBloc(),
        ),
        ChangeNotifierProvider<CartBloc>.value(
          value: CartBloc(),
        ),
        ChangeNotifierProvider<UserBloc>.value(
          value: UserBloc(),
        ),
        ChangeNotifierProvider<ThemeBloc>.value(
          value: ThemeBloc(),
        ),
      ],
      child: Main(),
    );
  }
}
```

No pubspec.yaml estou utilizando: "provider: any"

**Comment by andrebaltieri** [comment]
O erro diz que tentou ouvir um valor exposto fora da árvore de Widgets, minha sugestão é:

1 - Remover o `listen: false` que foi adicionado.
2 - Converter o Widget para Statefull
3 - Remover o parâmetro `context` do método `authenticate` e utilizar o contexto do Widget.

```dart
authenticate() async {
    var bloc = Provider.of<UserBloc>(context, listen: false);

    var user = await bloc.authenticate(
      new AuthenticateModel(
        username: username,
        password: password,
      ),
    );

    if (user != null) {
      Navigator.pop(context);
      return;
    }

    final snackBar = SnackBar(content: Text('Usuário ou senha invalidos'));
    _scaffoldKey.currentState.showSnackBar(snackBar);
  }
```

**Comment by rodrigoqb** [comment]
> O erro diz que tentou ouvir um valor exposto fora da árvore de Widgets, minha sugestão é:
> 
> 1 - Remover o `listen: false` que foi adicionado.
> 2 - Converter o Widget para Statefull
> 3 - Remover o parâmetro `context` do método `authenticate` e utilizar o contexto do Widget.
> 
> ```dart
> authenticate() async {
>     var bloc = Provider.of<UserBloc>(context, listen: false);
> 
>     var user = await bloc.authenticate(
>       new AuthenticateModel(
>         username: username,
>         password: password,
>       ),
>     );
> 
>     if (user != null) {
>       Navigator.pop(context);
>       return;
>     }
> 
>     final snackBar = SnackBar(content: Text('Usuário ou senha invalidos'));
>     _scaffoldKey.currentState.showSnackBar(snackBar);
>   }
> ```

Fiz as alterações, mas não surtiram efeito.

O account.page.dart deixei Stateless ainda pois como a gerência está sendo feita pelo BloC não tem necessidade, correto?

Alterei o authenticated-user-card.widget.dart e o unauthenticated-user-card.widget.dart:

```
class UnauthenticatedUserCard extends StatefulWidget {
  @override
  _UnauthenticatedUserCardState createState() =>
      _UnauthenticatedUserCardState();
}

class _UnauthenticatedUserCardState extends State<UnauthenticatedUserCard> {
  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: <Widget>[
        SizedBox(
          height: 60,
        ),
        FlatButton(
          child: Text("Autentique-se"),
          onPressed: () {
            Navigator.push(
              context,
              MaterialPageRoute(
                builder: (context) => LoginPage(),
              ),
            );
          },
        ),
        FlatButton(
          child: Text("Ainda não sou cadastrado"),
          onPressed: () {
            Navigator.push(
              context,
              MaterialPageRoute(
                builder: (context) => SignupPage(),
              ),
            );
          },
        ),
      ],
    );
  }
}
```

```
class AuthenticatedUserCard extends StatefulWidget {
  @override
  _AuthenticatedUserCardState createState() => _AuthenticatedUserCardState();
}

class _AuthenticatedUserCardState extends State<AuthenticatedUserCard> {
  @override
  Widget build(BuildContext context) {
    var bloc = Provider.of<UserBloc>(context);

    return Container(
      child: Center(
        child: Column(
          children: <Widget>[
            SizedBox(
              height: 20,
            ),
            Container(
              width: 200,
              height: 200,
              decoration: BoxDecoration(
                image: new DecorationImage(
                  fit: BoxFit.fill,
                  image: new NetworkImage(bloc.user.image),
                ),
                color: Theme.of(context).primaryColor,
                border: Border.all(
                  width: 4.0,
                  color: const Color(0xFFFFFFFF),
                ),
                borderRadius: BorderRadius.all(
                  Radius.circular(200),
                ),
              ),
            ),
            SizedBox(
              height: 20,
            ),
            Text("Bem-vindo, ${bloc.user.name}"),
            SizedBox(
              height: 10,
            ),
            FlatButton(
              child: Text("Sair"),
              onPressed: bloc.logout,
            ),
          ],
        ),
      ),
    );
  }
}
```

E aqui, o authenticate() da login.page.dart:

```
FlatButton(
   child: Text("Entrar"),
   onPressed: () {
   if (_formKey.currentState.validate()) {
        _formKey.currentState.save();
        authenticate();
       }
    },
  ),

authenticate() async {
    var bloc = Provider.of<UserBloc>(context);

    var user = await bloc.authenticate(
      new AuthenticateModel(
        username: username,
        password: password,
      ),
    );

    if (user != null) {
      Navigator.pop(context);
      return;
    }

    final snackBar = SnackBar(content: Text('Usuário ou senha invalidos'));
    _scaffoldKey.currentState.showSnackBar(snackBar);
  }
}
```

Era dessa forma que havia imaginado, Balta?

**Comment by andrebaltieri** [comment]
Quase @rodrigoqb, na verdade o ideal é você obter o bloc apenas uma vez, no build...
```
// Declara seu bloc no começo da classe

Widget build(BuildContext context) {
    // Só instancia ele aqui
    bloc = Provider.of<UserBloc>(context);
```
Ai no authenticate fica assim

```
authenticate() async {
    var user = await bloc.authenticate(
      new AuthenticateModel(
        username: username,
        password: password,
      ),
    );
```

**Comment by rodrigoqb** [comment]
> Quase @rodrigoqb, na verdade o ideal é você obter o bloc apenas uma vez, no build...
> 
> ```
> // Declara seu bloc no começo da classe
> 
> Widget build(BuildContext context) {
>     // Só instancia ele aqui
>     bloc = Provider.of<UserBloc>(context);
> ```
> 
> Ai no authenticate fica assim
> 
> ```
> authenticate() async {
>     var user = await bloc.authenticate(
>       new AuthenticateModel(
>         username: username,
>         password: password,
>       ),
>     );
> ```

Declarar o BloC como você sugeriu acima, resolveu os problemas e agora consigo me autenticar e redirecionar corretamente, eliminando o erro que estava dando.

Porém, só consegui atualizar o Widget da account.page.dart adicionando um notifyListeners() no authenticate() do user.bloc.dart:

```
Future<UserModel> authenticate(AuthenticateModel model) async {
    try {
      var prefs = await SharedPreferences.getInstance();
      var repository = new AccountRepository();

      var res = await repository.authenticate(model);

      user = res;

      await prefs.setString('user', jsonEncode(res));
      notifyListeners();
      return res;
    } catch (ex) {
      user = null;
      return null;
    }
  }
```

Agora o que está acontecendo é que no Hot Restart funciona tudo lindo, mantém o usuário logado e boa! Mas no Hot Reload, ele atualiza o Widget da account.page.dart e passa a mostrar sempre o unauthenticated-user-card.widget.dart.

Sabe algum motivo para isso? Já fiz os testes transformando-os em Stateful mas o problema persiste. O estranho é que no Hot Restart o usuário permanece autenticado, mas no Reload ele interpreta que não.

**Comment by andrebaltieri** [comment]
@rodrigoqb é o comportamento padrão visto que as variáveis foram limpas e embora a aplicação volte para página atual, nem tudo foi recarregado, como o usuário logado por exemplo.

Posso fechar esta issue?

**Comment by rodrigoqb** [comment]
> @rodrigoqb é o comportamento padrão visto que as variáveis foram limpas e embora a aplicação volte para página atual, nem tudo foi recarregado, como o usuário logado por exemplo.
> 
> Posso fechar esta issue?

Perfeito, Balta! Legal.

Problema resolvido então! Muito obrigado!

Pode fechar sim!
